export const SHOP_GAMES = [
  { id: 'all', name: 'Все игры' },
  { id: 'spy', name: 'Шпион' },
  { id: 'mafia', name: 'Мафия' },
  { id: 'elias', name: 'Элиас' },
  { id: 'truth_dare', name: 'Правда/Действие' },
  { id: 'bunker', name: 'Бункер' },
];
export const SHOP_CATEGORIES = [
  { id: 'all', name: 'Всё' },
  { id: 'dictionaries', name: 'Словари' },
  { id: 'modes', name: 'Режимы' },
  { id: 'packs', name: 'Паки' },
  { id: 'scenarios', name: 'Сценарии' },
];

export const SHOP_ITEMS = [
  { game: 'spy', category: 'dictionaries', id: 'spy_free', name: 'Базовый', description: 'Классические локации. Бесплатно.', emoji: '📍', free: true },
  { game: 'spy', category: 'dictionaries', id: 'spy_theme1', name: 'Детектив', description: 'Шпионы, агенты, шифры. Про.', emoji: '🕵️', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_theme2', name: 'Пираты', description: 'Корабли, сокровища, острова. Про.', emoji: '🏴‍☠️', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_travel', name: 'Путешествия', description: 'Аэропорт, отель, круиз. Про.', emoji: '✈️', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_food', name: 'Еда', description: 'Ресторан, кафе, кухня. Про.', emoji: '🍽️', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_sports', name: 'Спорт', description: 'Стадион, спортзал, бассейн. Про.', emoji: '⚽', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_movies', name: 'Кино', description: 'Кинотеатр, премьера, Оскар. Про.', emoji: '🎬', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_music', name: 'Музыка', description: 'Концерт, опера, студия. Про.', emoji: '🎵', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_nature', name: 'Природа', description: 'Лес, море, парк. Про.', emoji: '🌲', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_science', name: 'Наука', description: 'Лаборатория, обсерватория. Про.', emoji: '🔬', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_history', name: 'История', description: 'Замок, музей, руины. Про.', emoji: '🏛️', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_art', name: 'Искусство', description: 'Галерея, выставка. Про.', emoji: '🎨', free: false },
  { game: 'spy', category: 'dictionaries', id: 'spy_tech', name: 'Технологии', description: 'Офис, коворкинг, VR. Про.', emoji: '💻', free: false },
  { game: 'mafia', category: 'modes', id: 'mafia_extended', name: 'Расширенная Мафия', description: 'Дон, Комиссар, Доктор, Маньяк. Про.', emoji: '🌙', free: false },
  { game: 'elias', category: 'dictionaries', id: 'elias_basic', name: 'Базовый', description: 'Простые слова. Бесплатно.', emoji: '📦', free: true },
  { game: 'elias', category: 'dictionaries', id: 'elias_animals', name: 'Животные', description: 'Звери, птицы, рыбы. Бесплатно.', emoji: '🦁', free: true },
  { game: 'elias', category: 'dictionaries', id: 'elias_movies', name: 'Кино', description: 'Жанры, награды. Про.', emoji: '🎬', free: false },
  { game: 'elias', category: 'dictionaries', id: 'elias_science', name: 'Наука', description: 'Эксперименты, теории. Про.', emoji: '🔬', free: false },
  { game: 'elias', category: 'dictionaries', id: 'elias_sport', name: 'Спорт', description: 'Турниры, команды. Про.', emoji: '⚽', free: false },
  { game: 'truth_dare', category: 'packs', id: 'td_party', name: 'Party Pack', description: 'Больше драйва для большой компании. Про.', emoji: '🎉', free: false },
  { game: 'truth_dare', category: 'packs', id: 'td_18plus', name: '18+ Pack', description: 'Дополнительные взрослые категории. Про.', emoji: '🔞', free: false },
  { game: 'truth_dare', category: 'packs', id: 'td_romance', name: 'Romance Pack', description: 'Мягкий романтический формат. Про.', emoji: '💘', free: false },
  { game: 'bunker', category: 'scenarios', id: 'bunker_pandemic', name: 'Сценарий: Пандемия', description: 'Расширенный кризисный сценарий. Про.', emoji: '🧪', free: false },
  { game: 'bunker', category: 'scenarios', id: 'bunker_space', name: 'Сценарий: Орбита', description: 'Выживание в космической изоляции. Про.', emoji: '🛰️', free: false },
];
